export const LANGS = [
  { code: 'en', label: 'English', flag: 'EN', hreflang: 'en', rtl: false },
  { code: 'es', label: 'Español', flag: 'ES', hreflang: 'es', rtl: false },
  { code: 'fr', label: 'Français', flag: 'FR', hreflang: 'fr', rtl: false },
  { code: 'de', label: 'Deutsch', flag: 'DE', hreflang: 'de', rtl: false },
  { code: 'zh', label: '繁體中文', flag: 'ZH', hreflang: 'zh', rtl: false },
  { code: 'zh-Hans', label: '简体中文', flag: 'ZH-Hans', hreflang: 'zh-Hans', rtl: false },
  { code: 'ja', label: '日本語', flag: 'JA', hreflang: 'ja', rtl: false },
  { code: 'ar', label: 'العربية', flag: 'AR', hreflang: 'ar', rtl: true },
  { code: 'fa', label: 'فارسی', flag: 'FA', hreflang: 'fa', rtl: true },
  { code: 'hi', label: 'हिन्दी', flag: 'HI', hreflang: 'hi-IN', rtl: false },
  { code: 'pt', label: 'Português', flag: 'PT', hreflang: 'pt', rtl: false },
  { code: 'ru', label: 'Русский', flag: 'RU', hreflang: 'ru', rtl: false },
  { code: 'id', label: 'Bahasa Indonesia', flag: 'ID', hreflang: 'id', rtl: false },
  { code: 'it', label: 'Italiano', flag: 'IT', hreflang: 'it', rtl: false },
  { code: 'ko', label: '한국어', flag: 'KO', hreflang: 'ko', rtl: false },
  { code: 'tr', label: 'Türkçe', flag: 'TR', hreflang: 'tr', rtl: false },
  { code: 'vi', label: 'Tiếng Việt', flag: 'VI', hreflang: 'vi', rtl: false },
  { code: 'pl', label: 'Polski', flag: 'PL', hreflang: 'pl', rtl: false },
  { code: 'fil', label: 'Filipino', flag: 'FIL', hreflang: 'fil', rtl: false },
  { code: 'nl', label: 'Nederlands', flag: 'NL', hreflang: 'nl', rtl: false },
  { code: 'ur', label: 'اردو', flag: 'UR', hreflang: 'ur', rtl: true },
  { code: 'sw', label: 'Kiswahili', flag: 'SW', hreflang: 'sw', rtl: false }
];
