#!/usr/bin/env python3
"""
update_wiki_with_howker_and_disease_folders.py
------------------------------------------------

This script populates the White Mountains wiki directory with new plant
directories from a Cloudflare R2 bucket and ensures that all plant
disease folders exist.  It is intended to be run from the root of the
project repository (the directory containing the ``whitemountains-wiki``
folder).

The script performs two main tasks:

1. **Synchronise Howker plant images** (optional)
   When provided with an R2 bucket name and prefix, the script will use
   the AWS CLI to list directories in that bucket and create a matching
   directory structure under ``whitemountains-wiki/plants``.  If the
   ``--download-images`` flag is given, the script will also download
   the images for each new plant using ``aws s3 sync``.  To use this
   feature you must have the AWS CLI configured with credentials for
   your Cloudflare R2 account and specify the R2 endpoint via your
   ``~/.aws/config`` or the ``--endpoint-url`` parameter.

2. **Create disease directories**
   The script reads a JSON file containing plant disease entries
   (generated by earlier steps) and creates a directory under
   ``whitemountains-wiki/plant-diseases`` for each disease ``id``.  This
   ensures that the wiki contains a placeholder directory for every
   disease so that photos can be added later.

Usage examples:

  # Create disease folders only (no R2 sync)
  python update_wiki_with_howker_and_disease_folders.py \
      --plant-diseases-json wiki/plant_diseases.json

  # Create plant folders based on a bucket and download images
  python update_wiki_with_howker_and_disease_folders.py \
      --plant-diseases-json wiki/plant_diseases.json \
      --r2-bucket howker-plants \
      --r2-prefix howker_plants_imgs \
      --download-images

Notes:
  * The script requires Python 3.6 or later.
  * To download images you must have the AWS CLI installed and
    configured to talk to your Cloudflare R2 account.  See
    https://developers.cloudflare.com/r2/api/s3/ for configuration.
  * Directory creation is idempotent; running the script multiple times
    will not overwrite existing folders or images.
"""

import argparse
import json
import os
import subprocess
import sys
from typing import List, Set


def parse_arguments() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Populate whitemountains-wiki with directories for Howker plants and plant diseases."
        )
    )
    parser.add_argument(
        "--whitemountains-root",
        default="whitemountains-wiki",
        help=(
            "Path to the root of the whitemountains-wiki directory. "
            "If not specified, it defaults to 'whitemountains-wiki' in the current directory."
        ),
    )
    parser.add_argument(
        "--plant-diseases-json",
        required=True,
        help=(
            "Path to the JSON file containing plant disease entries. "
            "Each entry must have an 'id' field that will be used as the folder name."
        ),
    )
    parser.add_argument(
        "--r2-bucket",
        help=(
            "Name of the Cloudflare R2 bucket that contains the Howker plant images. "
            "If omitted, the script will skip creating plant folders from the bucket."
        ),
    )
    parser.add_argument(
        "--r2-prefix",
        default="howker_plants_imgs",
        help=(
            "Prefix inside the R2 bucket where plant folders are stored. "
            "Defaults to 'howker_plants_imgs'."
        ),
    )
    parser.add_argument(
        "--download-images",
        action="store_true",
        help=(
            "If set, synchronise image files from R2 for each new plant folder using "
            "'aws s3 sync'.  Requires AWS CLI to be installed and configured."
        ),
    )
    parser.add_argument(
        "--aws-endpoint",
        default=None,
        help=(
            "Optional custom endpoint URL for AWS CLI when downloading images from R2. "
            "If specified, it will be passed to the 'aws s3' commands via "
            "'--endpoint-url'."
        ),
    )
    return parser.parse_args()


def ensure_directory(path: str) -> None:
    """Create a directory if it doesn't already exist."""
    if not os.path.exists(path):
        os.makedirs(path, exist_ok=True)


def load_disease_ids(diseases_json_path: str) -> List[str]:
    """Load disease IDs from the given JSON file."""
    with open(diseases_json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    if isinstance(data, dict) and "diseases" in data:
        diseases = data["diseases"]
    elif isinstance(data, list):
        diseases = data
    else:
        raise ValueError(
            f"Unexpected format in {diseases_json_path}. Expected a list or dict with 'diseases' key."
        )
    ids: List[str] = []
    for entry in diseases:
        # Use the 'id' field if present; fall back to slugified 'name'.
        disease_id = entry.get("id")
        if not disease_id:
            name = entry.get("name") or entry.get("common_name") or "unknown-disease"
            disease_id = (
                name.lower()
                .replace(" ", "-")
                .replace("/", "-")
                .replace("__", "-")
            )
        ids.append(disease_id)
    return ids


def list_r2_plants(bucket: str, prefix: str, aws_endpoint: str = None) -> Set[str]:
    """
    Use the AWS CLI to list objects in the R2 bucket and extract unique plant folder names.

    Returns a set of plant names (folder names) found under the given prefix.  Requires
    that the AWS CLI be installed.  If the AWS CLI is not available, a RuntimeError
    will be raised.
    """
    if not bucket:
        return set()
    cmd = ["aws", "s3", "ls", f"s3://{bucket}/{prefix}/", "--recursive"]
    if aws_endpoint:
        cmd.extend(["--endpoint-url", aws_endpoint])
    try:
        result = subprocess.run(
            cmd,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
    except FileNotFoundError:
        raise RuntimeError(
            "AWS CLI not found. Please install the AWS CLI and configure it for your R2 bucket."
        )
    except subprocess.CalledProcessError as e:
        raise RuntimeError(
            f"Failed to list bucket contents. Command: {' '.join(cmd)}\n"
            f"Return code: {e.returncode}\n"
            f"Error output: {e.stderr}"
        )
    plant_names: Set[str] = set()
    for line in result.stdout.splitlines():
        # Example line: "2023-07-14 01:23:45    1234 howker_plants_imgs/alpine-bilberry/1.jpg"
        parts = line.split(maxsplit=3)
        if len(parts) < 4:
            continue
        key = parts[3].strip()
        # Remove prefix
        if key.startswith(prefix + "/"):
            key = key[len(prefix) + 1 :]
        # Extract the folder name (top-level component before slash)
        if "/" in key:
            plant_name = key.split("/", 1)[0]
        else:
            plant_name = key
        if plant_name:
            plant_names.add(plant_name)
    return plant_names


def create_plant_directories(
    plants_root: str,
    plant_names: Set[str],
    bucket: str,
    prefix: str,
    download_images: bool,
    aws_endpoint: str,
) -> None:
    """Create plant directories and optionally sync images from R2."""
    ensure_directory(plants_root)
    for plant in sorted(plant_names):
        local_dir = os.path.join(plants_root, plant)
        if os.path.exists(local_dir):
            # Already exists; skip creating or downloading again
            continue
        os.makedirs(local_dir, exist_ok=True)
        print(f"Created plant directory: {local_dir}")
        if download_images and bucket:
            # Use aws s3 sync to download images into this directory
            s3_path = f"s3://{bucket}/{prefix}/{plant}/"
            cmd = ["aws", "s3", "sync", s3_path, local_dir]
            if aws_endpoint:
                cmd.extend(["--endpoint-url", aws_endpoint])
            print(f"Synchronising images from {s3_path} to {local_dir}…")
            try:
                subprocess.run(cmd, check=True)
            except FileNotFoundError:
                print(
                    "WARNING: AWS CLI not found; skipping image download. "
                    "Install and configure the AWS CLI to enable downloads."
                )
            except subprocess.CalledProcessError as e:
                print(
                    f"WARNING: Failed to sync images for {plant}. Command: {' '.join(cmd)}\n"
                    f"Return code: {e.returncode}\n"
                    f"Error: {e}"
                )


def create_disease_directories(diseases_root: str, disease_ids: List[str]) -> None:
    """Create a directory for each disease ID under diseases_root."""
    ensure_directory(diseases_root)
    for disease_id in disease_ids:
        local_dir = os.path.join(diseases_root, disease_id)
        if os.path.exists(local_dir):
            continue
        os.makedirs(local_dir, exist_ok=True)
        print(f"Created disease directory: {local_dir}")


def main() -> None:
    args = parse_arguments()

    whitemountains_root = args.whitemountains_root
    diseases_json_path = args.plant_diseases_json
    bucket = args.r2_bucket
    prefix = args.r2_prefix
    download_images = args.download_images
    aws_endpoint = args.aws_endpoint

    # Ensure root exists
    ensure_directory(whitemountains_root)

    # Step 1: load disease IDs and create disease directories
    try:
        disease_ids = load_disease_ids(diseases_json_path)
    except Exception as e:
        print(f"Error reading disease JSON: {e}")
        sys.exit(1)
    disease_root = os.path.join(whitemountains_root, "plant-diseases")
    create_disease_directories(disease_root, disease_ids)

    # Step 2: list plant names from R2 (if bucket provided)
    plant_names: Set[str] = set()
    if bucket:
        try:
            plant_names = list_r2_plants(bucket, prefix, aws_endpoint)
        except RuntimeError as e:
            print(f"WARNING: {e}\nSkipping plant listing from R2.")
    if plant_names:
        plants_root = os.path.join(whitemountains_root, "plants")
        create_plant_directories(
            plants_root,
            plant_names,
            bucket,
            prefix,
            download_images,
            aws_endpoint,
        )


if __name__ == "__main__":
    main()